wandb_version: 1

learning_rate:
  desc: null
  value: 1.0e-06
momentum:
  desc: null
  value: 0.9
step_size:
  desc: null
  value: 30
gamma:
  desc: null
  value: 0.1
num_epochs:
  desc: null
  value: 200
dataset:
  desc: null
  value: bdd100
architecture:
  desc: null
  value: cnn
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696455650.472073
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.5
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
